question_design:
  description: >
    Design a set of questions to ask a group of people about {topic}.
    Make sure the questions are open-ended and can provide valuable insights.
  expected_output: >
    A singular question that is to be used to complete a online search about {topic}
  agent: question_designer

research_task:
  description: >
    Conduct a thorough research using the question provided by the question designer.
    Look through all ten links provided by the search engine and find the most insightful article. 
    Make sure you the search query is the question provided by the question designer. 
    the current date is {current_date}.
  expected_output: >
    One link to a relevant article or source that provides information about the question. Only repsond with the link and nothing else
  agent: researcher

web_scraping_task:
  description: >
    Extract data from websites provided by the researcher.
    Make sure you gather valuable information quickly and efficiently.
  expected_output: >
    The data extracted from the websites.
  agent: web_scraper

insight_generation_task:
  description: >
    Generate actionable insights from the data provided by the web scraper.
    Make sure the insights provoke more questions and lead to further research.
  expected_output: >
    A set of actionable insights that can be used to generate more questions and lead to further research.
  agent: insight_generator

question_design_task2:
  description: >
    Design a set of questions based on the insights generated by the insight generator.
    Make sure the questions are open-ended and can provide valuable insights.
  expected_output: >
    A questions that can be used to gather more information about the topic to be used in a search engine
  agent: question_designer2

research_task2:
  description: >
    Conduct a thorough research using the questions provided by the question designer.
    Look through all ten links provided by the search engine and find the most insightful article. 
    Make sure you the search query is the question provided by the question designer. 
    the current date is {current_date}.
  expected_output: >
    One link to a relevant article or source that provides information about the question. Only repsond with the link and nothing else
  agent: researcher

web_scraping_task2:
  description: >
    Extract data from websites related to the questions provided by the question designer.
    Make sure you gather valuable information quickly and efficiently.
  expected_output: >
    The data extracted from the websites.
  agent: web_scraper2

insight_generation_task2:
  description: >
    Generate actionable insights from the data provided by the web scraper.
    Make sure the insights provoke more questions and lead to further research.
  expected_output: >
    A set of actionable insights that can be used to generate more questions and lead to further research.
  agent: insight_generator

reporting_task:
  description: >
    Review the context you got from insight_generation1 and insight_generation 2 and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
